spring.application.name=spring-boot-benchmark

spring.datasource.url=jdbc:postgresql://localhost:5432/benchdb
spring.datasource.username=benchuser
spring.datasource.password=benchpass
spring.datasource.hikari.maximum-pool-size=50

server.port=8081

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true